export interface Product {
  id: string;
  name: Record<string, string>;
  description: Record<string, string>;
  shortDescription?: Record<string, string>;
  image: string;
  detailImages: string[];
  color: string;
  website?: string;
}

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    heroTitle: "Creating Value Through Customer Satisfaction",
    heroSubtitle: "A company that brings health and joy. This is the vision and mission of HKON.",
    exploreProducts: "Explore Products",
    company: "Company",
    products: "Products",
    support: "Support",
    resources: "Resources",
    ir: "Investor Relations",
    csr: "CSR",
    infoCenter: "Info Center",
    careers: "Careers",
    notice: "Notice",
    gallery: "Gallery",
    contactUs: "Contact Us",
    inquiry: "Product & Partnership Inquiry",
    inquiryManagement: "Inquiry Management",
    customerSupport: "Customer Center",
    training: "Careers",
    footerText: "© 2026 HKON. All rights reserved.",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    sitemap: "Sitemap",
    location: "Location",
    readMore: "Discover More",
    hkonKorea: "HKON Korea",
    hkon: "HKON",
    haagendazs: "Häagen-Dazs",
    haagendazsSub: "The Standard of Premium Ice Cream",
    haagendazsDesc: "Experience the rich and deep flavor of Häagen-Dazs, the standard of premium ice cream. Made with only the finest ingredients, it offers an unforgettable taste.",
    natureValley: "Nature Valley",
    natureValleySub: "Healthy Energy from Nature",
    natureValleyDesc: "Nature Valley Protein Bar Peanut Butter Dark Chocolate.\nA convenient way to get 10g of protein a day.\nThe perfect harmony of chewy peanuts and chocolate.",
    lantico: "L'Antico",
    lanticoSub: "Authentic Italian Taste",
    lanticoDesc: "Premium products made adhering to traditional Italian methods, delivering the authentic taste of Italy to your table.",
    caraci: "Caraci",
    caraciSub: "Flavor of Premium Pistachios",
    caraciDesc: "Caraci Pistachio Cream. A luxurious spread made with premium pistachios. Perfect for spreading on toast, adding to desserts, or enjoying straight from the jar.",
    fruitByTheFoot: "Fruit By The Foot",
    fruitByTheFootSub: "Fun to Unroll and Eat",
    fruitByTheFootDesc: "1M long roll-type jelly! Fun to unroll and eat.\nContains 12% fruit puree (berry & strawberry).\nPerfect for kids snacks, playtime, kindergarten/school events, and special gifts.",
    hkonDesc: "A specialized company that imports and distributes premium foods based on global sourcing capabilities.",
    generalMills: "General Mills",
    generalMillsSub: "Healthy Snacks & Fun Treats",
    generalMillsDesc: "Enjoy 10g of protein every day with the deliciously chewy Peanut Butter Dark Chocolate protein bars, and experience endless fun with the 1-meter long strawberry-flavored roll-type fruit jelly. Perfect snacks for all ages, lovingly made by the global food giant General Mills.",
    greenGiant: "Green Giant",
    greenGiantSub: "Fresh & Healthy",
    greenGiantDesc: "High quality canned vegetables for your healthy diet.",
    premiumQuality: "Premium Quality",
    feature1: "Carefully selected premium ingredients for the best taste and quality.",
    feature2: "Perfectly suited for your daily healthy lifestyle and balanced diet.",
    expertConsultation: "B2B / B2C Inquiries",
    remoteHelp: "Store & Distribution",
    smartMonitoring: "Product Catalogs",
    customizedTraining: "Join our team",
    customerCenter: "Customer Support",
    weekdays: "Weekdays 09:30 - 18:30",
    closedWeekends: "(Closed on Weekends & Holidays)",
    address: "164beon-gil, Samjak-ro, Bucheon-si, Gyeonggi-do, South Korea",
    globalNetwork: "Global Network",
    korea: "Korea (HQ)",
    usa: "USA",
    japan: "Japan",
    china: "China",
    europe: "Europe",
    quickLinks: "Quick Links",
    introDesc: "HK ON is a specialized company that imports and distributes premium foods based on global sourcing capabilities.",
    coreCompetency: "Core Competency",
    core1: "Official distribution partner for global premium brands (Häagen-Dazs, Caraci, General Mills, L'Antico, etc.)",
    core2: "Strict quality control and stable distribution system",
    core3: "Realizing high customer satisfaction centered on online channels",
    vision: "Vision",
    visionDesc: "Leading the premium dessert and convenience food market, we will leap forward as a premium F&B company that provides new value to both customers and partners through offline expansion (department stores, etc.).",
    aboutUs: "About Us",
    aboutUsTitle: "Delivering Global Tastes to Your Table",
    aboutUsDesc: "HKON discovers the world's most premium food brands and brings them closer to you.",
    whatsNew: "What's New?",
    whatsNewTitle: "Latest Highlights & Innovations",
    whatsNewDesc: "Stay updated with HKON's newest product launches, brand partnerships, and exciting events.",
    formCategory: "Category",
    formCategoryProduct: "Product & Brand Inquiry",
    formCategoryPartnership: "Partnership & Affiliation Inquiry",
    formCategoryOther: "Other Inquiry",
    formName: "Name / Company Name",
    formNamePlaceholder: "John Doe / HKON",
    formContact: "Contact Number",
    formContactPlaceholder: "010-0000-0000",
    formEmail: "Email Address",
    formEmailPlaceholder: "example@hkonkorea.com",
    formContent: "Inquiry Details",
    formContentPlaceholder: "Please enter your inquiry details.",
    formSubmit: "Submit Inquiry",
    formSubmitting: "Submitting...",
    formSuccessTitle: "Inquiry successfully submitted.",
    formSuccessDesc: "Our representative will review and reply as soon as possible.",
    formError: "An error occurred while submitting. Please try again later.",
    adminsOnly: "Admins only"
  },
  ko: {
    heroTitle: "글로벌 미식의 기준을 새롭게 정의하다",
    heroSubtitle: "에이치케이온(HKON)은 끊임없이 진화하는 미식 트렌드를 이끌어갑니다.",
    exploreProducts: "제품 자세히 보기",
    company: "기업 소개",
    products: "제품 소개",
    support: "고객 지원",
    resources: "미디어 자료실",
    ir: "투자 정보",
    csr: "지속가능경영(CSR)",
    infoCenter: "인포 센터",
    careers: "인재 채용",
    notice: "공지사항",
    gallery: "갤러리",
    contactUs: "문의하기",
    inquiry: "제품 문의, 입점 및 제휴 문의",
    inquiryManagement: "문의 관리",
    customerSupport: "고객 센터",
    training: "채용 안내",
    footerText: "© 2026 에이치케이온 코리아. All rights reserved.",
    privacyPolicy: "개인정보처리방침",
    termsOfService: "이용약관",
    sitemap: "사이트맵",
    location: "오시는 길",
    readMore: "스토리 더보기",
    hkonKorea: "에이치케이온 코리아",
    hkon: "에이치케이온",
    haagendazs: "하겐다즈",
    haagendazsSub: "프리미엄 아이스크림의 완벽한 기준",
    haagendazsDesc: "타협하지 않는 퀄리티로 완성된 하겐다즈의 깊고 진한 맛을 경험해 보세요. 전 세계에서 엄선된 100% 리얼 재료만이 선사할 수 있는 잊지 못할 풍미를 자랑합니다.",
    natureValley: "네이쳐밸리",
    natureValleySub: "자연이 빚어낸 건강한 에너지",
    natureValleyDesc: "네이쳐밸리 프로틴바 피넛버터 다크 초콜릿.\n바쁜 일상 속 하루 10g의 단백질을 가장 간편하고 맛있게 채우는 방법.\n리얼 초콜릿과 고소한 피넛의 환상적인 식감을 즐겨보세요.",
    lantico: "란티코",
    lanticoSub: "이탈리아 커피 장인의 숨결",
    lanticoDesc: "이탈리아 전통 로스팅 기법을 고스란히 담아낸 프리미엄 커피. 란티코 한 잔으로 이탈리아 피아짜(Piazza)에 앉아있는 듯한 진한 아로마와 깊은 여운을 만끽하세요.",
    caraci: "카라치",
    caraciSub: "시칠리아 피스타치오의 마법",
    caraciDesc: "시칠리아에서 자란 최고급 피스타치오만을 엄선해 만든 프리미엄 카라치 크림. 빵에 부드럽게 발라 먹거나 디저트에 곁들이면 평범한 식탁이 미슐랭 레스토랑의 디저트로 변신합니다.",
    fruitByTheFoot: "후룻바이더풋",
    fruitByTheFootSub: "돌돌 풀어먹는 끝없는 즐거움",
    fruitByTheFootDesc: "무려 1미터 길이로 돌돌 풀리는 재미만점 롤 타입 젤리!\n천연 과일 퓨레(베리&딸기)를 12% 함유해 안심하고 먹을 수 있습니다.\n아이들의 생일파티, 소풍, 어린이집 이벤트 간식으로 최고의 인기를 누리고 있습니다.",
    hkonDesc: "에이치케이온은 독보적인 글로벌 소싱 역량과 철저한 품질 관리를 바탕으로 프리미엄 식품을 국내에 선보이는 유통 전문 기업입니다.",
    generalMills: "제너럴밀즈",
    generalMillsSub: "자연의 건강함 & 즐거운 맛의 상상",
    generalMillsDesc: "하루 10g의 단백질을 쫀득한 식감으로 간편하게 채우는 고단백 피넛버터 다크 초콜릿 프로틴바와 무려 1미터 길이로 돌돌 풀어먹는 재미 가득한 천연 과일 젤리.\n영양가 높은 견과류와 과일 퓨레를 활용해 전 연령층에게 사랑받는 세계적인 식품 기업 제너럴밀즈의 대표 스낵을 에이치케이온에서 다채롭게 만나보세요.",
    greenGiant: "그린자이언트",
    greenGiantSub: "가장 신선한 순간을 담다",
    greenGiantDesc: "태양의 기운을 머금고 자란 채소를 가장 신선할 때 수확하여 그대로 담았습니다. 건강한 식단을 위한 고품질 스위트콘과 채소들을 만나보세요.",
    premiumQuality: "Premium Selection",
    feature1: "전 세계를 누비며 직접 발굴한 타협 없는 최고급 품질 인증.",
    feature2: "고객만족도 1위를 향한 까다롭고 철저한 콜드체인 유통 시스템.",
    expertConsultation: "B2B / B2C 납품 상담",
    remoteHelp: "신규 입점 및 파트너십",
    smartMonitoring: "공식 카탈로그 요청",
    customizedTraining: "인재 채용 풀 등록",
    customerCenter: "고객 지원 센터",
    weekdays: "평일 AM 09:30 - PM 06:30",
    closedWeekends: "(주말 및 법정공휴일 휴무)",
    address: "경기도 부천시 원미구 삼작로 164번길, 에이치케이온 코리아",
    globalNetwork: "글로벌 비즈니스 네트워크",
    korea: "한국 (Global HQ)",
    usa: "미주 지사",
    japan: "일본 지사",
    china: "중화권 지사",
    europe: "유럽 지사",
    quickLinks: "Quick Links",
    introDesc: "HK ON은 압도적인 글로벌 소싱 네트워크를 통해 세계 최상급 브랜드를 국내 소비자에게 이어주는 프리미엄 식품 유통사입니다.",
    coreCompetency: "핵심 경쟁력",
    core1: "하겐다즈, 카라치, 제너럴밀즈, 란티코 등 글로벌 프리미엄 브랜드의 공식 유통 파트너.",
    core2: "식품 안전과 신선도를 극대화하는 선진화된 통합 물류·유통 시스템 운영.",
    core3: "이커머스 채널을 아우르는 최적화된 마케팅으로 폭발적인 성장을 견인.",
    vision: "우리의 비전",
    visionDesc: "프리미엄 디저트 및 간편식 시장의 트렌드세터로 자리 잡으며, 백화점을 넘어 다각화된 오프라인 확장을 통해 파트너와 고객 모두의 라이프스타일을 끌어올리는 대체 불가 F&B 리더로 우뚝 서겠습니다.",
    aboutUs: "About Us",
    aboutUsTitle: "세상의 다채로운 맛을 식탁 위로",
    aboutUsDesc: "에이치케이온(HKON)은 끊임없이 진화하는 미식 트렌드를 이끌어갑니다.",
    whatsNew: "What's New?",
    whatsNewTitle: "가장 먼저 만나는 새로운 트렌드",
    whatsNewDesc: "에이치케이온이 새롭게 선보이는 신제품 라인업과 핫한 팝업 스토어, 특별한 브랜드 프로모션 소식을 가장 빠르게 확인하세요.",
    formCategory: "구분",
    formCategoryProduct: "제품 및 브랜드 문의",
    formCategoryPartnership: "입점 및 제휴 문의",
    formCategoryOther: "기타 문의",
    formName: "이름 / 회사명",
    formNamePlaceholder: "홍길동 / 에이치케이온",
    formContact: "연락처",
    formContactPlaceholder: "010-0000-0000",
    formEmail: "이메일 주소",
    formEmailPlaceholder: "example@hkonkorea.com",
    formContent: "문의 내용",
    formContentPlaceholder: "상세한 문의 내용을 입력해주세요.",
    formSubmit: "문의하기",
    formSubmitting: "접수 중...",
    formSuccessTitle: "문의가 성공적으로 접수되었습니다.",
    formSuccessDesc: "담당자가 확인 후 빠른 시일 내에 답변 드리겠습니다.",
    formError: "문의 접수 중 오류가 발생했습니다. 잠시 후 다시 시도해주세요.",
    adminsOnly: "관리자 전용"
  },
  zh: {
    heroTitle: "通过卓越的客户满意度创造非凡价值",
    heroSubtitle: "为您带来健康与喜悦的企业。这是 HKON 坚定不移的愿景和使命。",
    exploreProducts: "探索我们的产品",
    company: "公司简介",
    products: "产品介绍",
    support: "支持与服务",
    resources: "资源中心",
    ir: "投资者关系",
    csr: "企业社会责任",
    infoCenter: "信息中心",
    careers: "加入我们",
    notice: "最新公告",
    gallery: "媒体库",
    contactUs: "联系我们",
    inquiry: "产品、合作与分销咨询",
    inquiryManagement: "咨询管理",
    customerSupport: "客户中心",
    training: "招聘信息",
    footerText: "© 2026 HKON 韩国机构。保留所有权利。",
    privacyPolicy: "隐私政策",
    termsOfService: "服务条款",
    sitemap: "网站导航",
    location: "公司位置",
    readMore: "了解更多",
    hkonKorea: "HKON 韩国",
    hkon: "HKON",
    haagendazs: "哈根达斯 (Häagen-Dazs)",
    haagendazsSub: "尽享高级冰淇淋的非凡体验",
    haagendazsDesc: "体验哈根达斯浓郁醇厚的风味。仅使用最优质的原料制成，无论是质地还是味道，都是高端冰淇淋无可争议的标杆。",
    natureValley: "天然谷 (Nature Valley)",
    natureValleySub: "源自大自然的健康动能",
    natureValleyDesc: "天然谷花生酱黑巧克力蛋白棒。每天轻松摄取10克高质量蛋白质，浓郁的花生与黑巧克力的完美结合，让您活力满满。",
    lantico: "兰蒂科",
    lanticoSub: "纯正意大利咖啡的传承",
    lanticoDesc: "坚持意大利百年传统烘焙工艺，为您呈现香气浓郁、风味深沉的优质咖啡豆，将罗马街头的咖啡香带到您的餐桌。",
    caraci: "卡拉奇",
    caraciSub: "西西里开心果的奢华风味",
    caraciDesc: "卡拉奇开心果奶油。100%精选优质开心果制成的奢华涂抹酱。无论涂抹在吐司、可丽饼上，还是直接食用，都能带来无限惊喜。",
    fruitByTheFoot: "果丹皮卷 (Fruit By The Foot)",
    fruitByTheFootSub: "好吃又好玩的童年记忆",
    fruitByTheFootDesc: "长达1米的水果卷筒凝胶糖果！解开的一瞬间充满欢乐。含有12%的真实水果泥（草莓与混合浆果），是派对与零食的绝佳选择。",
    hkonDesc: "HKON 是一家依托强大的全球供应链，在韩国市场进口并经销顶级食品的专业机构。",
    generalMills: "通用磨坊",
    generalMillsSub: "健康零食与乐趣无边",
    generalMillsDesc: "每天轻松摄取10克高质量蛋白质的花生黑巧蛋白棒，以及长达1米的草莓风味水果卷筒凝胶糖果，每一口都充满童年回忆。\n精选了包含丰富营养的坚果与天然果蓉，无论是成人补充能量还是儿童创意零食，全球知名企业通用磨坊的代表产品都能为您带来健康与欢乐。",
    greenGiant: "绿巨人",
    greenGiantSub: "每一颗都饱含新鲜与健康",
    greenGiantDesc: "在蔬菜最甜美多汁的时候进行采摘加工，为您和家人的健康饮食提供最优质的罐装甜玉米和蔬菜选择。",
    premiumQuality: "臻选品质",
    feature1: "严格苛选全球最优质的原材料，确保每一口都充满最顶级的味觉体验。",
    feature2: "不仅仅是美味，更是完美契合现代人追求健康的平衡生活方式。",
    expertConsultation: "B2B / B2C 批发与零售咨询",
    remoteHelp: "卖场入驻与渠道拓展",
    smartMonitoring: "产品目录与宣传册下载",
    customizedTraining: "诚聘英才，加入我们",
    customerCenter: "全球客户服务中心",
    weekdays: "工作日 (周一至周五) AM 09:30 - PM 06:30",
    closedWeekends: "(周末及法定节假日休息)",
    address: "韩国京畿道富川市三作路164号街，HKON",
    globalNetwork: "全球战略网络",
    korea: "韩国 (全球总部)",
    usa: "美洲分部",
    japan: "日本分部",
    china: "大中华区分部",
    europe: "欧洲分部",
    quickLinks: "快捷导航",
    introDesc: "HKON 是一家基于全球采购能力，进口和分销高端食品的专业公司，致力于将全球美食带向亚洲。",
    coreCompetency: "企业核心竞争力",
    core1: "全球标志性高端品牌（哈根达斯、天然谷、兰蒂科等）在韩国的官方紧密合作伙伴。",
    core2: "从仓储到冷链，确保食品安全与新鲜度的行业领先物流系统。",
    core3: "紧抓电商趋势的热门营销，在数字渠道中创造持续高增长的客户满意度。",
    vision: "企业愿景",
    visionDesc: "作为高端甜点与便捷食品行业的领导者，我们将通过拓宽线下业务（精品百货商城等），打造为客户与商业伙伴创造持续价值的高端 F&B（餐饮）集团。",
    aboutUs: "关于我们",
    aboutUsTitle: "将世界各地美味汇聚在您的餐桌",
    aboutUsDesc: "HKON 引领着不断演进的美食潮流。我们精挑细选全球极具价值的品牌，为您呈现生活里绝妙的味蕾体验。",
    whatsNew: "最新资讯",
    whatsNewTitle: "前沿趋势与品牌动态",
    whatsNewDesc: "第一时间获取 HKON 全新引进的海外品牌、火爆的快闪店活动以及限时特别优惠等最新资讯。",
    formCategory: "类别",
    formCategoryProduct: "产品与品牌咨询",
    formCategoryPartnership: "合作与分销咨询",
    formCategoryOther: "其他咨询",
    formName: "姓名 / 公司名称",
    formNamePlaceholder: "张三 / HKON",
    formContact: "联系电话",
    formContactPlaceholder: "138-0000-0000",
    formEmail: "电子邮件",
    formEmailPlaceholder: "example@hkonkorea.com",
    formContent: "咨询内容",
    formContentPlaceholder: "请输入详细的咨询内容。",
    formSubmit: "提交咨询",
    formSubmitting: "提交中...",
    formSuccessTitle: "咨询已成功提交。",
    formSuccessDesc: "我们的代表将在确认后尽快回复您。",
    formError: "提交咨询时发生错误。请稍后再试。",
    adminsOnly: "仅限管理员"
  }
};

export const PRODUCTS: Product[] = [
  {
    id: 'haagen-dazs',
    name: { en: 'Häagen-Dazs', ko: '하겐다즈', zh: '哈根达斯' },
    description: { 
      en: 'Experience the rich and deep flavor of Häagen-Dazs, the standard of premium ice cream. Made with only the finest ingredients, it offers an unforgettable taste.',
      ko: '프리미엄 아이스크림의 완벽한 기준, 하겐다즈.\n타협하지 않는 퀄리티로 완성된 하겐다즈의 깊고 진한 맛을 경험해 보세요. 전 세계에서 엄선된 100% 리얼 재료만이 선사할 수 있는 잊지 못할 풍미를 자랑합니다.',
      zh: '体验哈根达斯浓郁醇厚的风味。仅使用最优质的原料制成，无论是质地还是味道，都是高端冰淇淋无可争议的标杆。'
    },
    shortDescription: {
      en: 'The standard of premium ice cream, offering unforgettable deep flavor.',
      ko: '프리미엄 아이스크림의 완벽한 기준, 하겐다즈. 타협 없는 퀄리티로 완성된 풍미를 만나보세요.',
      zh: '高端冰淇淋标杆，无论质地还是味道都无可争议。'
    },
    image: '/images/mini_cup.png',
    detailImages: ['/images/stick_bar.png', '/images/paint.png'],
    color: '#D4AF37',
    website: 'https://www.haagendazs.co.kr/'
  },
  {
    id: 'lantico',
    name: { en: "L'Antico", ko: '란티코', zh: "L'Antico" },
    description: { 
      en: 'Premium coffee beans with rich aroma and deep flavor.',
      ko: '이탈리아 피아짜의 정통 커피, 란티코.\n이탈리아 전통 로스팅 기법을 고스란히 담아낸 프리미엄 커피. 란티코 한 잔으로 이탈리아 피아짜(Piazza)에 앉아있는 듯한 진한 아로마와 깊은 여운을 만끽하세요.',
      zh: '香气浓郁、风味深沉的优质咖啡豆。坚持意大利百年传统烘焙工艺，将罗马街头的咖啡香带到您的餐桌。'
    },
    shortDescription: {
      en: 'Premium Italian coffee beans with rich aroma and deep flavor.',
      ko: '이탈리아 피아짜의 정통 커피, 란티코. 깊은 여운의 아로마를 선사합니다.',
      zh: '坚持意大利百年传统的优质咖啡豆，香气浓郁。'
    },
    image: '/images/lantico.png',
    detailImages: ['/images/lantico_2.png'],
    color: '#3B2F2F',
    website: 'https://www.caffelantico.it/'
  },
  {
    id: 'caraci',
    name: { en: 'Caraci', ko: '카라치', zh: '卡拉奇' },
    description: { 
      en: 'Caraci Pistachio Cream. A luxurious spread made with premium pistachios. Perfect for spreading on toast, adding to desserts, or enjoying straight from the jar.',
      ko: '시칠리아 피스타치오의 마법, 카라치.\n시칠리아에서 자란 최고급 피스타치오만을 엄선해 만든 프리미엄 단스프레드 크림. 빵에 부드럽게 발라 먹거나 디저트에 곁들이면 평범한 식탁이 미슐랭 레스토랑 디저트로 변신합니다.',
      zh: '卡拉奇开心果奶油。100%精选优质开心果制成的奢华涂抹酱。无论涂抹在吐司、可丽饼上，还是直接食用，都能带来无限惊喜。'
    },
    shortDescription: {
      en: 'A luxurious pistachio cream made with premium Sicilian pistachios.',
      ko: '시칠리아에서 자란 최고급 피스타치오만을 엄선해 만든 프리미엄 스프레드.',
      zh: '100%精选西西里开心果制成的奢华奶油涂抹酱。'
    },
    image: '/images/kadaif_thumbnail.png',
    detailImages: ['/images/kadaif.png', '/images/dark_choco_thumbnail.png'],
    color: '#AAB85C',
    website: 'https://www.caraci.it/'
  },
  {
    id: 'general-mills',
    name: { en: 'General Mills', ko: '제너럴밀즈', zh: '通用磨坊' },
    description: { 
      en: 'General Mills brings you Nature Valley and Fruit By The Foot. Enjoy protein bars with the harmony of peanuts and chocolate, and 1-meter roll-type jelly full of fun and strawberry flavor.',
      ko: '세계적인 식품 기업 제너럴밀즈의 대표 스낵 베스트셀러 브랜드를 만나보세요. 하루 10g의 단백질을 쫀득한 식감으로 간편하게 채우는 피넛버터 다크 초콜릿 프로틴바와 무려 1미터 길이로 돌돌 풀어먹는 재미 가득한 천연 과일 퓨레 젤리로 맛과 건강을 동시에 즐기실 수 있습니다.',
      zh: '通用磨坊精心挑选的健康零食品牌。每天轻松摄取10克高质量蛋白质的花生黑巧蛋白棒，以及长达1米的草莓风味水果卷筒凝胶糖果，每一口都充满童年快乐回忆。'
    },
    shortDescription: {
      en: 'Global snacks bringing health and joy with Nature Valley and Fruit By The Foot.',
      ko: '세계적인 식품 브랜드 제너럴밀즈. 자연의 건강함과 먹는 즐거움을 선사합니다.',
      zh: '提供美味与乐趣的全球知名零食品牌。'
    },
    image: '/images/grnaola_thumbnail.png',
    detailImages: [
      '/images/fruit_by_the_foot.png',
      '/images/granola_600_1.png',
      '/images/granola_600_2.png',
      '/images/granola_600_3.png',
      '/images/granola_600_4.png',
      '/images/granola_600_6.png'
    ],
    color: '#D03C36',
    website: 'https://www.generalmills.com/'
  }
];

export const LANGUAGES = [
  { code: 'ko', name: 'Korean' },
  { code: 'en', name: 'English' },
  { code: 'zh', name: 'Chinese' }
];
