export interface Product {
  id: string;
  name: Record<string, string>;
  description: Record<string, string>;
  image: string;
  detailImages: string[];
  color: string;
}

export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: {
    heroTitle: "Creating Value Through Customer Satisfaction",
    heroSubtitle: "A company that brings health and joy. This is the vision and mission of HKON.",
    exploreProducts: "View Details",
    company: "Company",
    products: "Products",
    support: "Support",
    resources: "Resources",
    ir: "IR",
    csr: "CSR",
    infoCenter: "Info Center",
    careers: "Careers",
    notice: "Notice",
    gallery: "Gallery",
    contactUs: "Contact Us",
    inquiry: "Product Inquiry",
    remoteSupport: "Partnership",
    customerSupport: "Customer Center",
    training: "Careers",
    footerText: "© 2026 HKON. All rights reserved.",
    privacyPolicy: "Privacy Policy",
    termsOfService: "Terms of Service",
    sitemap: "Sitemap",
    location: "Location",
    readMore: "Read More",
    hkonKorea: "HKON Korea",
    hkon: "HKON",
    haagendazs: "Häagen-Dazs",
    haagendazsSub: "The Standard of Premium Ice Cream",
    haagendazsDesc: "Experience the rich and deep flavor of Häagen-Dazs, the standard of premium ice cream. Made with only the finest ingredients, it offers an unforgettable taste.",
    natureValley: "Nature Valley",
    natureValleySub: "Healthy Energy from Nature",
    natureValleyDesc: "Nature Valley Protein Bar Peanut Butter Dark Chocolate.\nA convenient way to get 10g of protein a day.\nThe perfect harmony of chewy peanuts and chocolate.",
    lantico: "L'Antico",
    lanticoSub: "Authentic Italian Taste",
    lanticoDesc: "Premium products made adhering to traditional Italian methods, delivering the authentic taste of Italy to your table.",
    caraci: "Caraci",
    caraciSub: "Flavor of Premium Pistachios",
    caraciDesc: "Caraci Pistachio Cream. A luxurious spread made with premium pistachios. Perfect for spreading on toast, adding to desserts, or enjoying straight from the jar.",
    fruitByTheFoot: "Fruit By The Foot",
    fruitByTheFootSub: "Fun to Unroll and Eat",
    fruitByTheFootDesc: "1M long roll-type jelly! Fun to unroll and eat.\nContains 12% fruit puree (berry & strawberry).\nPerfect for kids snacks, playtime, kindergarten/school events, and special gifts.",
    hkonDesc: "A specialized company that imports and distributes premium foods based on global sourcing capabilities.",
    greenGiant: "Green Giant",
    greenGiantSub: "Fresh & Healthy",
    greenGiantDesc: "High quality canned vegetables for your healthy diet.",
    premiumQuality: "Premium Quality",
    feature1: "Carefully selected premium ingredients for the best taste and quality.",
    feature2: "Perfectly suited for your daily healthy lifestyle and balanced diet.",
    expertConsultation: "B2B / B2C Inquiries",
    remoteHelp: "Store & Distribution",
    smartMonitoring: "Product Catalogs",
    customizedTraining: "Join our team",
    customerCenter: "Customer Center",
    weekdays: "Weekdays 09:30 - 18:30",
    closedWeekends: "(Closed on Weekends & Holidays)",
    address: "164beon-gil, Samjak-ro, Bucheon-si, Gyeonggi-do",
    globalNetwork: "Global Network",
    korea: "Korea (HQ)",
    usa: "USA",
    japan: "Japan",
    china: "China",
    europe: "Europe",
    quickLinks: "Quick Links",
    introDesc: "HK ON is a specialized company that imports and distributes premium foods based on global sourcing capabilities.",
    coreCompetency: "Core Competency",
    core1: "Official distribution partner for global premium brands (Häagen-Dazs, Caraci, General Mills, L'Antico, etc.)",
    core2: "Strict quality control and stable distribution system",
    core3: "Realizing high customer satisfaction centered on online channels",
    vision: "Vision",
    visionDesc: "Leading the premium dessert and convenience food market, we will leap forward as a premium F&B company that provides new value to both customers and partners through offline expansion (department stores, etc.)."
  },
  ko: {
    heroTitle: "고객 만족을 통한 가치 창조",
    heroSubtitle: "건강하고 기쁨을 주는 기업, 에이치케이온의 비전과 미션입니다.",
    exploreProducts: "자세히 보기",
    company: "회사소개",
    products: "제품소개",
    support: "고객지원",
    resources: "자료실",
    ir: "투자정보",
    csr: "사회공헌",
    infoCenter: "정보센터",
    careers: "채용정보",
    notice: "공지사항",
    gallery: "갤러리",
    contactUs: "Contact Us",
    inquiry: "제품 문의",
    remoteSupport: "입점/제휴 문의",
    customerSupport: "고객 센터",
    training: "채용 정보",
    footerText: "© 2026 에이치케이온. All rights reserved.",
    privacyPolicy: "개인정보처리방침",
    termsOfService: "이용약관",
    sitemap: "사이트맵",
    location: "오시는길",
    readMore: "더보기",
    hkonKorea: "에이치케이온 코리아",
    hkon: "에이치케이온",
    haagendazs: "하겐다즈",
    haagendazsSub: "프리미엄 아이스크림의 기준",
    haagendazsDesc: "프리미엄 아이스크림의 기준, 하겐다즈의 깊고 진한 풍미를 경험해보세요. 엄선된 최고의 재료만을 사용하여 잊을 수 없는 맛을 선사합니다.",
    natureValley: "네이처밸리",
    natureValleySub: "자연에서 온 건강한 에너지",
    natureValleyDesc: "네이처밸리 프로틴바 피넛버터 다크 초콜릿\n하루 10g 간편한 단백질 섭취\n피넛과 초콜릿의 쫀득한 조화",
    lantico: "란티코",
    lanticoSub: "이탈리아 정통의 맛",
    lanticoDesc: "이탈리아 전통 방식을 고수하여 만든 프리미엄 제품으로, 정통 이탈리아의 맛을 식탁에 전달합니다.",
    caraci: "카라치",
    caraciSub: "최고급 피스타치오의 풍미",
    caraciDesc: "카라치 피스타치오 크림. 최고급 피스타치오로 만든 럭셔리한 스프레드입니다. 토스트에 발라 먹거나 디저트에 추가하거나 그대로 즐기기에 완벽합니다.",
    fruitByTheFoot: "후룻바이더풋",
    fruitByTheFootSub: "도르르 풀어먹는 재미",
    fruitByTheFootDesc: "1M 길이의 롤 타입 젤리로 도르르 풀어먹는 재미!\n12% 과일 퓨레 함유(베리&딸기).\n아이 간식 및 놀이 타임, 유치원/학교 이벤트 간식, 특별한 날 선물로 완벽합니다.",
    hkonDesc: "글로벌 소싱 역량을 기반으로 프리미엄 식품을 수입·유통하는 전문 기업입니다.",
    greenGiant: "그린자이언트",
    greenGiantSub: "신선하고 건강한",
    greenGiantDesc: "건강한 식단을 위한 고품질 캔 채소입니다.",
    premiumQuality: "프리미엄 퀄리티",
    feature1: "최고의 맛과 품질을 위해 엄선된 프리미엄 원재료를 사용합니다.",
    feature2: "건강한 라이프스타일과 균형 잡힌 식단에 완벽하게 어울립니다.",
    expertConsultation: "B2B / B2C 제품 문의",
    remoteHelp: "유통 및 입점 제안",
    smartMonitoring: "제품 카탈로그 다운로드",
    customizedTraining: "함께 성장할 인재 영입",
    customerCenter: "고객센터",
    weekdays: "평일 09:30 - 18:30",
    closedWeekends: "(주말 및 공휴일 휴무)",
    address: "경기도 부천시 삼작로 164번길",
    globalNetwork: "글로벌 네트워크",
    korea: "한국 (본사)",
    usa: "미국",
    japan: "일본",
    china: "중국",
    europe: "유럽",
    quickLinks: "빠른 링크",
    introDesc: "HK ON은 글로벌 소싱 역량을 기반으로 프리미엄 식품을 수입·유통하는 전문 기업입니다.",
    coreCompetency: "핵심 경쟁력",
    core1: "글로벌 프리미엄 브랜드(하겐다즈, 카라치, 제너럴밀즈, 란티코 등) 공식 유통 파트너",
    core2: "철저한 품질 관리 및 안정적인 유통 시스템",
    core3: "온라인 채널 중심의 높은 고객 만족도 실현",
    vision: "비전",
    visionDesc: "프리미엄 디저트 및 간편식 시장을 선도하며, 오프라인 확장(백화점 등)을 통해 고객과 파트너 모두에게 새로운 가치를 제공하는 프리미엄 F&B 기업으로 도약합니다."
  },
  zh: {
    heroTitle: "通过客户满意创造价值",
    heroSubtitle: "一家带来健康和快乐的公司。这是 HKON 的愿景和使命。",
    exploreProducts: "查看详情",
    company: "公司",
    products: "产品",
    support: "支持",
    resources: "资源",
    ir: "投资者关系",
    csr: "企业社会责任",
    infoCenter: "信息中心",
    careers: "职业生涯",
    notice: "公告",
    gallery: "画廊",
    contactUs: "联系我们",
    inquiry: "产品查询",
    remoteSupport: "入驻/合作查询",
    customerSupport: "客户中心",
    training: "招聘信息",
    footerText: "© 2026 HKON。版权所有。",
    privacyPolicy: "隐私政策",
    termsOfService: "服务条款",
    sitemap: "网站地图",
    location: "位置",
    readMore: "阅读更多",
    hkonKorea: "HKON 韩国",
    hkon: "HKON",
    haagendazs: "哈根达斯",
    haagendazsSub: "高级冰淇淋的标杆",
    haagendazsDesc: "体验哈根达斯浓郁醇厚的风味，高级冰淇淋的标杆。仅使用最优质的原料制成，提供令人难忘的口感。",
    natureValley: "自然谷",
    natureValleySub: "来自大自然的健康能量",
    natureValleyDesc: "自然谷花生酱黑巧克力蛋白棒。\n每天方便摄取10克蛋白质。\n耐嚼花生和巧克力的完美结合。",
    lantico: "兰蒂科",
    lanticoSub: "正宗意大利风味",
    lanticoDesc: "坚持意大利传统工艺制作的高端产品，将正宗的意大利风味带到您的餐桌上。",
    caraci: "卡拉奇",
    caraciSub: "优质开心果的风味",
    caraciDesc: "卡拉奇开心果奶油。用优质开心果制成的奢华涂抹酱。非常适合涂抹在吐司上，添加到甜点中，或直接从罐子里享用。",
    fruitByTheFoot: "水果卷",
    fruitByTheFootSub: "解开吃很有趣",
    fruitByTheFootDesc: "1米长的卷型果冻！解开吃很有趣。\n含有12%的水果泥（浆果和草莓）。\n非常适合儿童零食、游戏时间、幼儿园/学校活动和特殊礼物。",
    hkonDesc: "一家基于全球采购能力进口和分销高端食品的专业公司。",
    greenGiant: "绿巨人",
    greenGiantSub: "新鲜健康",
    greenGiantDesc: "为您的健康饮食提供优质罐装蔬菜。",
    premiumQuality: "优质品质",
    feature1: "精心挑选优质原料，确保最佳口感和品质。",
    feature2: "非常适合您日常健康的生活方式和均衡的饮食。",
    expertConsultation: "B2B / B2C 产品查询",
    remoteHelp: "分销和入驻建议",
    smartMonitoring: "下载产品目录",
    customizedTraining: "加入我们的团队",
    customerCenter: "客户中心",
    weekdays: "工作日 09:30 - 18:30",
    closedWeekends: "(周末及节假日休息)",
    address: "京畿道富川市三作路164号街",
    globalNetwork: "全球网络",
    korea: "韩国 (总部)",
    usa: "美国",
    japan: "日本",
    china: "中国",
    europe: "欧洲",
    quickLinks: "快速链接",
    introDesc: "HK ON 是一家基于全球采购能力进口和分销高端食品的专业公司。",
    coreCompetency: "核心竞争力",
    core1: "全球高端品牌（哈根达斯、Caraci、通用磨坊、L'Antico 等）的官方分销合作伙伴",
    core2: "严格的质量控制和稳定的分销系统",
    core3: "以在线渠道为中心实现高客户满意度",
    vision: "愿景",
    visionDesc: "引领高端甜点和方便食品市场，通过线下扩张（百货商店等），致力于成为为客户和合作伙伴提供新价值的餐饮企业。"
  }
};

export const PRODUCTS: Product[] = [
  {
    id: 'green-giant',
    name: { en: 'Green Giant', ko: '그린자이언트', zh: '绿巨人' },
    description: { 
      en: 'Premium quality canned vegetables harvested at the peak of freshness. Green Giant brings the natural goodness and crisp texture of farm-fresh vegetables straight to your table. Perfect for healthy, balanced meals.',
      ko: '최상의 신선도를 자랑할 때 수확한 프리미엄 품질의 채소. 그린자이언트는 농장에서 갓 수확한 채소의 자연스러운 풍미와 아삭한 식감을 식탁까지 그대로 전달합니다. 건강하고 균형 잡힌 식단에 완벽한 선택입니다.',
      zh: '在最新鲜的时候收获的优质罐装蔬菜。绿巨人将农场新鲜蔬菜的自然美味和清脆口感直接带到您的餐桌上。健康均衡膳食的完美选择。'
    },
    image: '/images/green_giant.jpg',
    detailImages: [
      '/images/green_giant_1.jpg',
      '/images/green_giant_2.jpg',
      '/images/green_giant_3.jpg',
      '/images/green_giant_4.jpg',
      '/images/green_giant_5.jpg'
    ],
    color: '#34d399'
  },
  {
    id: 'nature-valley',
    name: { en: 'Nature Valley', ko: '네이쳐밸리', zh: '自然谷' },
    description: { 
      en: 'Nature Valley Protein Bar Peanut Butter Dark Chocolate. A convenient way to get 10g of protein a day. The perfect harmony of chewy peanuts and chocolate.',
      ko: '네이처밸리 프로틴바 피넛버터 다크 초콜릿\n하루 10g 간편한 단백질 섭취\n피넛과 초콜릿의 쫀득한 조화',
      zh: '自然谷花生酱黑巧克力蛋白棒。每天方便摄取10克蛋白质。耐嚼花生和巧克力的完美结合。'
    },
    image: '/images/grnaola_thumbnail.jpg',
    detailImages: [
      '/images/granola_600_1.jpg',
      '/images/granola_600_2.jpg',
      '/images/granola_600_3.jpg',
      '/images/granola_600_4.jpg',
      '/images/granola_600_6.jpg'
    ],
    color: '#E08E8E'
  },
  {
    id: 'lantico',
    name: { en: "L'Antico", ko: '란티코', zh: "L'Antico" },
    description: { 
      en: 'Premium coffee beans with rich aroma and deep flavor.',
      ko: '풍부한 아로마와 깊은 풍미를 자랑하는 프리미엄 커피 원두입니다.',
      zh: '香气浓郁、风味深沉的优质咖啡豆。'
    },
    image: '/images/lantico.jpg',
    detailImages: ['/images/lantico_2.jpg'],
    color: '#8B5A2B'
  },
  {
    id: 'caraci',
    name: { en: 'Caraci Pistachio Cream', ko: '카라치 피스타치오 크림', zh: '卡拉奇开心果奶油' },
    description: { 
      en: 'Caraci Pistachio Cream. A luxurious spread made with premium pistachios. Perfect for spreading on toast, adding to desserts, or enjoying straight from the jar.',
      ko: '카라치 피스타치오 크림. 최고급 피스타치오로 만든 럭셔리한 스프레드입니다. 토스트에 발라 먹거나 디저트에 추가하거나 그대로 즐기기에 완벽합니다.',
      zh: '卡拉奇开心果奶油。用优质开心果制成的奢华涂抹酱。非常适合涂抹在吐司上，添加到甜点中，或直接从罐子里享用。'
    },
    image: '/images/kadaif_thumbnail.png',
    detailImages: ['/images/kadaif.jpg', '/images/dark_choco_thumbnail.png', '/images/dark_choco1.jpg'],
    color: '#4B3621'
  },
  {
    id: 'haagen-dazs',
    name: { en: 'Häagen-Dazs', ko: '하겐다즈', zh: '哈根达斯' },
    description: { 
      en: 'Experience the rich and deep flavor of Häagen-Dazs, the standard of premium ice cream. Made with only the finest ingredients, it offers an unforgettable taste.',
      ko: '프리미엄 아이스크림의 기준, 하겐다즈의 깊고 진한 풍미를 경험해보세요. 엄선된 최고의 재료만을 사용하여 잊을 수 없는 맛을 선사합니다.',
      zh: '体验哈根达斯浓郁醇厚的风味，高级冰淇淋的标杆。仅使用最优质的原料制成，提供令人难忘的口感。'
    },
    image: '/images/mini_cup.jpg',
    detailImages: ['/images/stick_bar.jpg', '/images/paint.jpg'],
    color: '#F3E5AB'
  },
  {
    id: 'fruit-by-the-foot',
    name: { en: 'Fruit By The Foot', ko: '후룻바이더풋', zh: '水果卷' },
    description: { 
      en: '1M long roll-type jelly! Fun to unroll and eat. Contains 12% fruit puree (berry & strawberry). Perfect for kids snacks, playtime, kindergarten/school events, and special gifts.',
      ko: '1M 길이의 롤 타입 젤리로 도르르 풀어먹는 재미!\n12% 과일 퓨레 함유(베리&딸기).\n아이 간식 및 놀이 타임, 유치원/학교 이벤트 간식, 특별한 날 선물로 완벽합니다.',
      zh: '1米长的卷型果冻！解开吃很有趣。含有12%的水果泥（浆果和草莓）。非常适合儿童零食、游戏时间、幼儿园/学校活动和特殊礼物。'
    },
    image: '/images/fruit_by_the_foot.jpg',
    detailImages: [
      '/images/fruit_by_the_foot.jpg',
      '/images/fruit_by_the_foot.jpg',
      '/images/fruit_by_the_foot.jpg'
    ],
    color: '#8A9A5B'
  }
];

export const LANGUAGES = [
  { code: 'ko', name: 'Korean' },
  { code: 'en', name: 'English' },
  { code: 'zh', name: 'Chinese' }
];
